version: "3.7"

services:
  embed-base:
    platform: linux/amd64
    build:
      context: ./embed-base
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=latest
    image: "embed-base:latest"

  simple-wiki-jupyter:
    platform: linux/amd64
    depends_on:
      - embed-base
    build:
      context: ./simple-wiki-jupyter
      dockerfile: Dockerfile
    image: "simple-wiki-jupyter:dev"
    ports:
      - "8888:8888"
    volumes:
      - "./mounted_dirs/models:/home/jupyter/models"
      - "./mounted_dirs/notebooks:/home/jupyter/notebooks"
      - "./mounted_dirs/data:/home/jupyter/data"
  simple-wiki-jupyter-sf:
    depends_on:
      - simple-wiki-jupyter
    extends: simple-wiki-jupyter
    image: "${SF_REPO}/simple-wiki-jupyter:dev"

  simple-wiki-job:
    depends_on:
      - embed-base
    platform: linux/amd64
    build:
      context: ./simple-wiki-job
      dockerfile: Dockerfile
    image: "simple-wiki-job:dev"
    volumes:
      - "./mounted_dirs/models:/root/models"
      - "./mounted_dirs/data:/root/data"

  simple-wiki-job-sf:
    depends_on:
      - simple-wiki-job
    extends: simple-wiki-job
    image: "${SF_REPO}/simple-wiki-job:dev"

  simple-wiki-fastapi:
    depends_on:
      - embed-base
    platform: linux/amd64
    build:
      context: ./simple-wiki-fastapi
      dockerfile: Dockerfile
    image: "simple-wiki-fastapi:dev"
    ports:
      - "8080:80"
    volumes:
      - "./mounted_dirs/models:/root/models"
      - "./mounted_dirs/data:/root/data"

  simple-wiki-fastapi-sf:
    depends_on:
      - simple-wiki-fastapi
    extends: simple-wiki-fastapi
    image: "${SF_REPO}/simple-wiki-fastapi:dev"
